Brown/Karaoke/src/com/teamtreehouse/SPDEX450/metadataPackage_1626139407852/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Brown/Karaoke/src/com/teamtreehouse/SPDEX450/force-app/main/default/classes/OppHandler.cls
public with sharing class OppHandler {
    public OppHandler() {

    }

    public void updateOppName(List<Opportunity> opps){
        Set<Id> acctIds = new Set<Id>(); 
    for (Opportunity opp : opps){
        acctIds.add(opp.AccountId);
    }

    Map<Id,String> acctNames = new Map<Id,String>();
    for (Account acct : [SELECT Name FROM Account WHERE Id IN :acctIds]){
       acctNames.put(acct.Id, acct.Name); 
    }

    for (Opportunity opp: opps){
        opp.Name = acctNames.get(opp.AccountId) + '-'
        + opp.Type + '-' + opp.CloseDate.year() + '/'
        + opp.CloseDate.month();
    }
    }

    public void createInvoiceFromOpp(List<Opportunity> opps){ //This is the version for Insert
        List<Invoice__c> invToCreate = new List<Invoice__c>();
    for (Opportunity opp : opps){
        if (opp.isWon){
                Invoice__c inv = new Invoice__c();
                inv.Account__c = opp.AccountId;
                inv.Opportunity__c = opp.Id;
                inv.Billing_Contact__c = opp.ContactId;
                inv.Amount__c = opp.Amount;
                inv.Due_Date__c = opp.CloseDate + 30;
                invToCreate.add(inv);
        }
    }
    if (!invToCreate.isEmpty()){
        Database.insert(invToCreate,false);
    }
    }
    public void createInvoiceFromOpp(List<Opportunity> opps, Map<Id,Opportunity> oldOpps){ //This is the version for Update
        List<Invoice__c> invToCreate = new List<Invoice__c>();
    for (Opportunity opp : opps){
        if (opp.isWon && !oldOpps.get(opp.Id).isWon){
                Invoice__c inv = new Invoice__c();
                inv.Account__c = opp.AccountId;
                inv.Opportunity__c = opp.Id;
                inv.Billing_Contact__c = opp.ContactId;
                inv.Amount__c = opp.Amount;
                inv.Due_Date__c = opp.CloseDate + 30;
                invToCreate.add(inv);
        }
    }
    if (!invToCreate.isEmpty()){
        Database.insert(invToCreate,false);
    }
    }
}