Brown/Karaoke/src/com/teamtreehouse/SPDEX450/metadataPackage_1626139407852/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Brown/Karaoke/src/com/teamtreehouse/SPDEX450/force-app/main/default/classes/InvoicesController.cls
public with sharing class InvoicesController {
    private Id oid;
    private Opportunity o;

    public InvoicesController(ApexPages.StandardSetController ssc) {
        oid = ApexPages.currentPage().getParameters().get('id');
        loadOpportunity();
    }

    private void loadOpportunity(){
        o = [SELECT AccountId FROM Opportunity WHERE Id = :oid];
    }

    public List<Invoice__c> newinvoices {
        get{
          if (newinvoices == null){
              newinvoices = new List<Invoice__c>();

          for (Integer i=0; i < 12; i++){
              Invoice__c inv = new Invoice__c();
              inv.Opportunity__c = oid;
              inv.Account__c = o.AccountId;
            newInvoices.add(inv);
          }
        }
        return newinvoices;
        }
        set{}
    }

    public Pagereference save() {
        List<Invoice__c> invoicesToCreate = new List<Invoice__c>();
    
        for (Invoice__c inv : newInvoices){
            if (inv.Amount__c > 0) {
                invoicesToCreate.add(inv);
            }
        }
        insert invoicesToCreate;

        PageReference pr = new PageReference('/'+oid);
        return pr;
    }

    public Pagereference cancel() {
        PageReference pr = new PageReference('/'+oid);
        return pr;
    }
}